In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('example_data/sp_dump/CPMI_Diagnoser.parquet', engine='pyarrow')
df

,CPR_hash,Diagnosekode,Diagnose,Noteret_dato,Løst_dato
0,485d57c654236bd28359d69fbc9ef13cc145751a17a679...,D644,syndrome of the muscle (D644),2014-10-11,2016-05-15
1,4334fa46397c37e783ee5f7976fea313978e0ce4d8b5ae...,D378,syndrome of the muscle,2007-05-02,2017-10-29
2,5126baa03fbd518d3fb950dfef8dc924e62efea6670c5f...,D430,malformation of the eye (D430),2005-01-11,2019-11-09
3,da1a2dc65841ac26959fee3aa8492768b6ef5f4aab4806...,D626,disorder of the heart (D626),2024-10-20,2014-04-12
4,a4dff72f6a379021cf78a944249bf5a4687f71ed07d03a...,D276,syndrome of the skin (D276),2010-01-18,2018-02-05
...,...,...,...,...,...
495,7c0b48ce8b1a161a5c49fc3ad50e2aa889c64fbfc5baf2...,D517,malformation of the ear (D517),2017-11-29,2024-10-05
496,75ea1f8970cfcbeb1b4aaff5dcf35862a675cddde4cb92...,D200,unspecified of the liver (D200),2007-06-06,1997-10-08
497,fa0067dc02b1cc10ce00f9a35d104b952f391f2628c73e...,D306,malformation of the liver,2019-06-15,2020-03-24
498,9f863219c349a93685376991243b15da2ea8e2961263c0...,D329,collapse of the lung (D329),2019-12-28,2018-07-17
499,d71ab66e6d2ef3c4db4c3ec6e20f797523eaad26b163a9...,D794,disorder of the kidney (D794),2001-05-14,1994-06-22

In [3]:
diag_df = pd.read_parquet('../outputs/MEDS/shard_events/diagnosis/[0-500).parquet', engine='pyarrow')
diag_df.head()

     code  subject_id            timestamp
0  D/D644          31  2014-10-11 00:00:00
1  D/D378          28  2007-05-02 00:00:00
2  D/D430          33  2005-01-11 00:00:00
3  D/D626          85  2024-10-20 00:00:00
4  D/D276          70  2010-01-18 00:00:00

In [4]:
meds_df = pd.read_parquet('../outputs/MEDS/data/train/0.parquet', engine='pyarrow')
meds_df.head()

   subject_id                time            code  numeric_value
0           2                 NaT  GENDER//Kvinde            NaN
1           2 2014-05-26 00:00:00             DOB            NaN
2           2 2016-03-27 00:00:00          D/D261            NaN
3           2 2017-07-24 00:00:00          D/D258            NaN
4           2 2018-08-29 18:36:03   ADMISSION_ADT            NaN